### ISSUE TITLE
Monitor 5:4 is not supported

### ISSUE THREAD

**Issue by fifa000001** [Naimad1CZ/LeapingElements#2]
Its not possible to see, how many lifes has fire hero left.

![Snímek obrazovky (118)](https://user-images.githubusercontent.com/55358457/97760395-6186ad00-1b03-11eb-8eb9-950b0506462f.png)

**Comment by Naimad1CZ** [comment]
It's not caused by the screen ratio, but the fact that this game has only possible resolution of 1472x768 pixels, which is completely fine for FullHD monitors which are a standard nowadays.

Only possible resolution is caused by the fact that I wrote whole game (and rendering) engine myself and wanted to show always some reasonable number of blocks - 23x12. Also, the blocks are images of resolution 64x64 pixels, which means that shrinking the size of blocks would be probably quite a lot of additional work and that the graphics would look probably much worse.
