### ISSUE TITLE
Jumping on the top 

### ISSUE THREAD

**Issue by fifa000001** [Naimad1CZ/LeapingElements#3]
Jumping on the top is not so smooth if the other hero is down - camera do some nasty things up there....

For example if during the first level you will jump on the top platform with fire hero and you start jumping there, while ice one is swinmming in the pool, it s quite pain for eyes.

![Snímek obrazovky (119)](https://user-images.githubusercontent.com/55358457/97761276-93007800-1b05-11eb-84c5-b423e0883165.png)
![Snímek obrazovky (120)](https://user-images.githubusercontent.com/55358457/97761278-93990e80-1b05-11eb-9ecb-d50d9c147d56.png)

**Comment by Naimad1CZ** [comment]
The problem is that

**Comment by Naimad1CZ** [comment]
The problem is that I needed to implement some way how to view both heroes if possible, but to not try to view them if they are too far away (this holds even for the cases when you have a one hero at the side of the screen and don't see what is near him) - in this case focus on only one of them. So when the heroes are far away, but they would still fit on the screen, this "issue" might happen. But in this case it's the best to change camera focus with button C to keep the camera focus only on one of them.
